using OAuthWorks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace ExampleWebApiProject
{
    [DataContract]
    public class AuthorizationCodeResponse : IAuthorizationCodeResponse
    {
        /// <summary>
        /// Gets the code that was generated by the authorization server. REQUIRED.
        /// </summary>
        [DataMember(Name="code")]
        public string Code
        {
            get;
            set;
        }

        /// <summary>
        /// Gets the state that was sent by the client in the Authorization Request.REQUIRED ONLY IF the state was sent in the request.
        /// </summary>
        [DataMember(Name="state")]
        public string State
        {
            get;
            set;
        }
    }
}