// Copyright 2014 Kallyn Gowdy
// 
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace OAuthWorks.Implementation
{
    /// <summary>
    /// Defines a class that provides a basic implementation of <see cref="OAuthWorks.IAuthorizationCodeResponse"/>.
    /// </summary>
    [DataContract]
    public class AuthorizationCodeResponse : IAuthorizationCodeResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationCodeResponse"/> class.
        /// </summary>
        /// <param name="code">The authorization code that is granted to the client.</param>
        /// <param name="state">The state that the client provided.</param>
        public AuthorizationCodeResponse(string code, string state)
        {
            Contract.Requires(!string.IsNullOrEmpty(code));
            Contract.Requires(!string.IsNullOrEmpty(state));
            this.Code = code;
            this.State = state;
        }

        /// <summary>
        /// Gets the code that was generated by the authorization server. REQUIRED.
        /// </summary>
        [DataMember(Name = "code")]
        public string Code
        {
            get;
            protected set;
        }

        /// <summary>
        /// Gets the state that was sent by the client in the Authorization Request. REQUIRED ONLY IF the state was sent in the request.
        /// </summary>
        [DataMember(Name = "state")]
        public string State
        {
            get;
            protected set;
        }
    }
}
